src/Entity/Tag.php
<?php

namespace App\Entity;

use App\Repository\TagRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: TagRepository::class)]
#[UniqueEntity(fields: ['name'], message: 'Ce tag existe déjà')]
#[UniqueEntity(fields: ['slug'], message: 'Ce slug existe déjà')]
class Tag
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    /**
     * @var Collection<int, Project>
     */
    #[ORM\ManyToMany(targetEntity: Project::class, mappedBy: 'tag')]
    private Collection $projects;

    #[ORM\Column(length: 255)]
    private ?string $color = null;

    public function __construct()
    {
        $this->projects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): static
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->addTag($this);
        }

        return $this;
    }

    public function removeProject(Project $project): static
    {
        if ($this->projects->removeElement($project)) {
            $project->removeTag($this);
        }

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): static
    {
        $this->color = $color;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\DTO\ContactDTO;
use App\Entity\Post;
use App\Entity\Project;
use App\Form\ContactType;
use App\Repository\FaqRepository;
use App\Repository\LegalRepository;
use App\Repository\PostRepository;
use App\Repository\PostTagRepository;
use App\Repository\ProjectRepository;
use App\Repository\ReviewRepository;
use App\Repository\TagRepository;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Attribute\Route;

#[Route('', name: 'app_')]
class MainController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(ProjectRepository $projectRepository, PostRepository $postRepository, FaqRepository $faqRepository, ReviewRepository $reviewRepository): Response
    {
        $projects = $projectRepository->findBy(['is_homepage' => true]);
        $posts = $postRepository->findBy(['is_homepage' => true]);
        $faqs = $faqRepository->findBy(['category' => 'general']);
        $reviews = $reviewRepository->findAll();

        return $this->render('main/index.html.twig', [
            'projects' => $projects,
            'faqs' => $faqs,
            'posts' => $posts,
            'reviews' => $reviews,
        ]);
    }

    #[Route('/studio', name: 'studio')]
    public function studio(ReviewRepository $reviewRepository, FaqRepository $faqRepository): Response
    {
        $reviews = $reviewRepository->findAll();
        $faqs = $faqRepository->findBy(['category' => 'general']);

        return $this->render('main/studio.html.twig', [
            'reviews' => $reviews,
            'faqs' => $faqs
        ]);
    }

    #[Route('/tarifs', name: 'prices')]
    public function prices(): Response
    {
        return $this->render('main/prices.html.twig');
    }

    #[Route('/realisations', name: 'projects')]
    public function projects(ProjectRepository $repository, TagRepository $tagRepository): Response
    {
        $projects = $repository->findAll();
        $tags = $tagRepository->findAll();

        return $this->render('main/projects.html.twig', [
            'projects' => $projects,
            'tags' => $tags,
        ]);
    }

    #[Route('/realisations/{slug}', name: 'show')]
    public function show(Project $project, ProjectRepository $projectRepository): Response
    {
        $projects = $projectRepository->findById($project->getId());

        return $this->render('main/show.html.twig', [
            'project' => $project,
            'projects' => $projects,
        ]);
    }

    #[Route('/articles', name: 'posts')]
    public function posts(PostRepository $postRepository, PostTagRepository $postTagRepository): Response
    {
        $posts = $postRepository->findAll();
        $tags = $postTagRepository->findAll();

        return $this->render('main/posts.html.twig', [
            'posts' => $posts,
            'tags' => $tags,
        ]);
    }

    #[Route('/articles/{slug}', name: 'post')]
    public function post(Post $post, PostRepository $postRepository): Response
    {
        $posts = $postRepository->findById($post->getId());

        return $this->render('main/post.html.twig', [
            'post' => $post,
            'posts' => $posts,
        ]);
    }

    #[Route('/faq', name: 'faq')]
    public function faq(FaqRepository $faqRepository): Response
    {
        $faqs = $faqRepository->findAll();

        return $this->render('main/faq.html.twig', [
            'faqs' => $faqs,
        ]);
    }

    #[Route('/contact', name: 'contact')]
    public function contact(Request $request, MailerInterface $mailer): Response
    {
        $data = new ContactDTO();
        $form = $this->createForm(ContactType::class, $data);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $email = (new TemplatedEmail())
                ->from('hello@studiokhi.com')
                ->to('stefan@studiokhi.com')
                ->replyTo($data->email)
                ->cc('cynthia@studiokhi.com')
                ->subject('Nouveau message depuis studiokhi.com')
                ->htmlTemplate('emails/contact.html.twig')
                ->context([
                    'data' => $data
                ]);
            try {
                $mailer->send($email);
            } catch (TransportExceptionInterface $e) {
                echo $e->getMessage();
            }

            $this->addFlash('success', 'Votre message a bien été envoyé');
            return $this->redirectToRoute('app_contact');
        }

        return $this->render('main/contact.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/mentions-legales', name: 'legal_notice')]
    public function legalNotice(LegalRepository $legalRepository): Response
    {
        $legal = $legalRepository->findOneBy(['id' => 1]);
        return $this->render('legal/legal-notice.html.twig', [
            'legal' => $legal
        ]);
    }

    #[Route('/politique-de-confidentialite', name: 'privacy_policy')]
    public function privacyPolicy(LegalRepository $legalRepository): Response
    {
        $legal = $legalRepository->findOneBy(['id' => 1]);
        return $this->render('legal/privacy-policy.html.twig', [
            'legal' => $legal
        ]);
    }

    #[Route('/cookies', name: 'cookies')]
    public function cookies(LegalRepository $legalRepository): Response
    {
        $legal = $legalRepository->findOneBy(['id' => 1]);
        return $this->render('legal/cookies.html.twig', [
            'legal' => $legal
        ]);
    }
}

templates/main/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Contact - {{ parent() }}
{% endblock %}

{% block meta %}
    <meta name="description" content="Vous souhaitez recevoir un devis sur mesure ? Remplissez le formulaire de contact et parlez-nous de votre projet. Nous avons hâte d'écouter votre projet.">
    <meta property="og:title" content="Contact - Studio Khi" />
    <meta property="og:description" content="Vous souhaitez recevoir un devis sur mesure ? Remplissez le formulaire de contact et parlez-nous de votre projet. Nous avons hâte d'écouter votre projet." />
    <meta property="og:url" content="https://studiokhi.com{{ path('app_contact') }}" />
    {{ parent() }}
{% endblock %}

{% block body %}

    <section class="container__large border--bottom border-stroke-light">
        <div class="container">
            <h1>Parlons de votre projet</h1>
        </div>
    </section>
    <section class="container grid grid--2 grid-gap--6 grid--1-mobile">
        <div class="h-auto flex col justify--space-between">
            <p class="text__l w--50 w-100-mobile">
                Remplissez le formulaire de contact ci-dessous et parlez-nous de votre projet.
            </p>
            <button-react class="hide-mobile" data-content="Demander un devis" data-href="#"></button-react>
        </div>
        <div>
            {{ form_start(form, {'attr': {'class': 'flex col gap--5 w-100'}}) }}
                <div class="grid grid--2 grid--1-mobile grid-gap--5">
                    <div class="flex col gap--1">
                        {{ form_label(form.lastname) }}
                        {{ form_widget(form.lastname) }}
                        <div class="errors">
                            {{ form_errors(form.lastname) }}
                        </div>
                    </div>
                    <div class="flex col gap--1">
                        {{ form_label(form.firstname) }}
                        {{ form_widget(form.firstname) }}
                        <div class="errors">
                            {{ form_errors(form.firstname) }}
                        </div>
                    </div>
                    <div class="flex col gap--1">
                        {{ form_label(form.email) }}
                        {{ form_widget(form.email) }}
                        <div class="errors">
                            {{ form_errors(form.email) }}
                        </div>
                    </div>
                    <div class="flex col gap--1">
                        {{ form_label(form.phone) }}
                        {{ form_widget(form.phone) }}
                        <div class="errors">
                            {{ form_errors(form.phone) }}
                        </div>
                    </div>
                </div>
                <div class="flex col gap--1">
                    {{ form_label(form.message) }}
                    {{ form_widget(form.message) }}
                    <div class="errors">
                        {{ form_errors(form.message) }}
                    </div>
                </div>
                <div class="flex col gap--1">
                    {{ form_widget(form.captcha) }}
                    <div class="errors">
                        {{ form_errors(form.captcha) }}
                    </div>
                </div>
                <button type="submit" class="btn btn__dark">
                    Envoyer au studio
                    <svg class="btn__icon" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
                        <path d="M4.5 13.5L13.5 4.5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M6.1875 4.5H13.5V11.8125" stroke-width="1.5" stroke-linecap="round"
                              stroke-linejoin="round"/>
                    </svg>
                </button>
            {{ form_end(form) }}
        </div>
    </section>
    <section class="container__large secondary-beige--bg">
        <div class="container grid grid--3 grid-gap--4 grid--1-mobile">
            <div class="flex col gap--1 text-center text-left-mobile">
                <p class="primary-grey text__s">
                    Email
                </p>
                <p class="text__m">
                    hello@studiokhi.com
                </p>
            </div>
            <div class="flex col gap--1 text-center text-left-mobile">
                <p class="primary-grey text__s">
                    Téléphone
                </p>
                <p class="text__m">
                    09 87 19 28 88
                </p>
            </div>
            <div class="flex col gap--1 text-center text-left-mobile">
                <p class="primary-grey text__s">
                    Studio
                </p>
                <p class="text__m">
                    Remote depuis les Pyrénées
                </p>
            </div>
        </div>
    </section>

{% endblock %}

templates/main/faq.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    FAQ - {{ parent() }}
{% endblock %}

{% block meta %}
    <meta name="description" content="Nous avons peut-être déjà les réponses à vos questions ! Ne manquez pas notre FAQ pour trouver les réponses dont vous avez besoin.">
    <meta property="og:title" content="FAQ - Studio Khi" />
    <meta property="og:description" content="Nous avons peut-être déjà les réponses à vos questions ! Ne manquez pas notre FAQ pour trouver les réponses dont vous avez besoin." />
    <meta property="og:url" content="https://studiokhi.com{{ path('app_faq') }}" />
{% endblock %}

{% block body %}
    <section class="container flex col gap--16 gap-large-mobile align--start">
        <h1>Des questions ?</h1>
        <p class="w--60 w-100-mobile text__l align--self-end">
            Nous avons peut-être déjà les réponses à vos questions ! Ne manquez pas notre FAQ pour trouver les réponses
            dont vous avez besoin.
        </p>
    </section>
    <section class="container__large border--top border--bottom border-stroke-light">
        <div class="container container__scroll pt--11 pb--11 flex row align--center justify--center justify--start-mobile gap--5">
            <filter-react data-id="general" data-content="Général"></filter-react>
            <filter-react data-id="branding" data-content="Branding & Logo"></filter-react>
            <filter-react data-id="webdesign" data-content="Webdesign & UI/UX Design"></filter-react>
            <filter-react data-id="website" data-content="Site Web & Développement"></filter-react>
        </div>
    </section>
    <section class="container flex row col-mobile gap-large-mobile">
        <p class="text__l w--40 w-100-mobile">
            FAQ
        </p>
        <div class="w--60 w-100-mobile flex col align--start justify--start">
            {% for key, faq in faqs %}
                <article class="w--100 {{ faq.category }}">
                    <faq-react class="w--100" data-id="{{ key }}" data-title="{{ faq.question }}"
                               data-content="{{ faq.answer }}"></faq-react>
                </article>
            {% endfor %}
        </div>
    </section>
    <section class="container__large secondary-beige--bg">
        <div class="container flex col align--center justify--center gap--11 text-center">
            <h2 class="w--70 w-100-mobile">
                Autre chose ?
            </h2>
            <button-react data-href="{{ path('app_contact') }}"
                          data-content="Contactez-nous directement"></button-react>
        </div>
    </section>

{% endblock %}

templates/main/post.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ post.name }} - {{ parent() }}
{% endblock %}

{% block meta %}
    <meta name="description" content="Chaque projet est une histoire à part entière, reflétant notre passion pour le design et notre volonté de satisfaire nos clients. ">
    <meta property="og:title" content="{{ post.name }} - Studio Khi" />
    <meta property="og:description" content="Chaque projet est une histoire à part entière, reflétant notre passion pour le design et notre volonté de satisfaire nos clients. " />
    <meta property="og:url" content="https://studiokhi.com{{ path('app_post', {slug: post.slug}) }}" />
    {{ parent() }}
{% endblock %}

{% block body %}
    <section class="container__large border--bottom border-stroke-light">
        <div class="container flex col gap--16 gap-large-mobile align--start justify--start">
            <h1>{{ post.name }}</h1>
        </div>
    </section>
    <section class="container flex row col-mobile gap-small-mobile">
        <div class="flex col gap--11 text__l w--40 w-100-mobile">
            <div class="flex col gap--5">
                {% for tag in post.tag.toArray %}
                    <tag-react data-color="{{ tag.color }}" data-content="{{ tag.name }}"></tag-react>
                {% endfor %}
                <p class="text__m">Par {{ post.author|raw }}</p>
                <p class="text__m">{{ post.updatedAt|date("d/m/Y") }}</p>
            </div>
        </div>
        <div class="w--60 w-100-mobile flex col align--start justify--start gap--11 text__m">
            {{ post.content|raw }}
        </div>
    </section>
    <section class="container__large secondary-beige--bg">
        <div class="container flex row col-mobile align--end justify--space-between align--center-mobile gap-large-mobile">
            <h3 class="w--50 w-100-mobile text-center-mobile">Vous souhaitez travailler avec nous ?</h3>
            <div class="flex row col-mobile align--center justify--center gap--5">
                <button-react data-content="Commencer votre projet" data-href="#" data-color="light"></button-react>
                <button-react data-content="Prendre contact" data-href="#"></button-react>
            </div>
        </div>
    </section>
    <section class="container flex col gap--16 gap-large-mobile align--start justify--center">
        <div class="flex row col-mobile gap-small-mobile w--100">
            <p class="text__l w--40 w-100-mobile">
                Lire un autre article
            </p>
            <div class="w--50 w-100-mobile flex col align--start justify--start gap--11">
                <h3>
                    Vous avez encore deux minutes ?
                </h3>
            </div>
        </div>
        <div class="grid grid--2 grid-gap--5 row grid--1-mobile">
            {% for post in posts %}
                <article class="flex col gap--5 article {% for tag in post.tag.toArray %}{{ tag.slug }}{% endfor %}">
                    <a class="relative" href="{{ path('app_post', {slug: post.slug}) }}" aria-label="{{ post.name }}">
                        {% if post.image is not empty %}
                            <img class="home__img home__img-post" src="{{ asset('uploads/posts/featured/medium/') ~ post.image }}"
                                 loading="lazy" alt="{{ post.name }}">
                        {% else %}
                            <div class="home__img home__img-post stroke-dark--bg"></div>
                        {% endif %}
                        <div class="absolute pos-t--4 pos-l--4 flex row col-mobile gap--2">
                            {% for tag in post.tag.toArray %}
                                <tag-react data-color="{{ tag.color }}" data-content="{{ tag.name }}"></tag-react>
                            {% endfor %}
                        </div>
                        <svg class="absolute pos-center" width="125" height="125" viewBox="0 0 125 125" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle id="Ellipse 1" cx="62.5" cy="62.5" r="62.5" fill="white"/>
                            <path id="Vector" d="M49.5 75.5L74.5 50.5" stroke="#191919" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path id="Vector_2" d="M54.1875 50.5H74.5V70.8125" stroke="#191919" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </a>
                    <a href="{{ path('app_post', {slug: post.slug}) }}" class="flex col gap--3">
                        <p class="text__l">
                            {{ post.name }}
                        </p>
                        <link-react data-href="{{ path('app_post', {slug: post.slug}) }}" data-border="1" data-content="Lire l'article"></link-react>
                    </a>
                </article>
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/main/posts.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Les Articles - {{ parent() }}
{% endblock %}

{% block meta %}
    <meta name="description" content="Vous proposer notre vision et nos réflexions sur le design, le web et la stratégie digitale par notre sélection d’articles.">
    <meta property="og:title" content="Les Articles - Studio Khi" />
    <meta property="og:description" content="Vous proposer notre vision et nos réflexions sur le design, le web et la stratégie digitale par notre sélection d’articles." />
    <meta property="og:url" content="https://studiokhi.com{{ path('app_posts') }}" />
    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="container flex col gap--16 gap-large-mobile align--start">
        <h1>Articles & Blog</h1>
        <p class="w--60 w-100-mobile text__l align--self-end">
            Vous proposer notre vision et nos réflexions sur le design, le web et la stratégie digitale par notre sélection d’articles.
        </p>
    </div>
    <div class="container__large border--top border--bottom border-stroke-light">
        <div class="container container__scroll pt--11 pb--11 flex row align--center justify--center justify--start-mobile gap--5">
            <filter-react data-id="all" data-content="Tous les articles"></filter-react>
            {% for tag in tags %}
                <filter-react data-id="{{ tag.slug }}" data-content="{{ tag.name }}"></filter-react>
            {% endfor %}
        </div>
    </div>
    <section class="container flex col gap--16 gap-large-mobile align--start justify--center">
        <div class="grid grid--2 grid-gap--5 row grid--1-mobile">
            {% for post in posts %}
                <article class="flex col gap--5 article mb--20 {% for tag in post.tag.toArray %}{{ tag.slug }}{% endfor %}">
                    <a class="relative" href="{{ path('app_post', {slug: post.slug}) }}" aria-label="{{ post.name }}">
                        {% if post.image is not empty %}
                            <img class="home__img home__img-post" src="{{ asset('uploads/posts/featured/medium/') ~ post.image }}"
                                 loading="lazy" alt="{{ post.name }}">
                        {% else %}
                            <div class="home__img home__img-post stroke-dark--bg"></div>
                        {% endif %}
                        <div class="absolute pos-t--4 pos-l--4 flex row col-mobile gap--2">
                            {% for tag in post.tag.toArray %}
                                <tag-react data-color="{{ tag.color }}" data-content="{{ tag.name }}"></tag-react>
                            {% endfor %}
                        </div>
                        <svg class="absolute pos-center" width="125" height="125" viewBox="0 0 125 125" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle id="Ellipse 1" cx="62.5" cy="62.5" r="62.5" fill="white"/>
                            <path id="Vector" d="M49.5 75.5L74.5 50.5" stroke="#191919" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path id="Vector_2" d="M54.1875 50.5H74.5V70.8125" stroke="#191919" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </a>
                    <a href="{{ path('app_post', {slug: post.slug}) }}" class="flex col gap--3">
                        <p class="text__l">
                            {{ post.name }}
                        </p>
                        <link-react data-href="{{ path('app_post', {slug: post.slug}) }}" data-border="1" data-content="Lire l'article"></link-react>
                    </a>
                </article>
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/main/projects.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nos Réalisations - {{ parent() }}
{% endblock %}

{% block meta %}
    <meta name="description" content="Découvrez une série de projets sur lesquels nous avons travaillé, allant de la création d'identités visuelles à la conception de sites web.">
    <meta property="og:title" content="Réalisations - Studio Khi" />
    <meta property="og:description" content="Découvrez une série de projets sur lesquels nous avons travaillé, allant de la création d'identités visuelles à la conception de sites web." />
    <meta property="og:url" content="https://studiokhi.com{{ path('app_projects') }}" />
    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="container flex col gap--16 gap-large-mobile align--start">
        <h1>Nos Réalisations</h1>
        <p class="w--60 w-100-mobile text__l align--self-end">
            Découvrez une série de projets sur lesquels nous avons travaillé, allant de la création d'identités
            visuelles à la conception de sites web. Chaque projet est une histoire à part entière, reflétant notre
            passion pour le design et notre volonté de satisfaire nos clients.
        </p>
    </div>
    <div class="container__large border--top border--bottom border-stroke-light">
        <div class="container container__scroll pt--11 pb--11 flex row align--center justify--center justify--start-mobile gap--5">
            <filter-react data-id="all" data-content="Tous les projets"></filter-react>
            {% for tag in tags %}
                <filter-react data-id="{{ tag.slug }}" data-content="{{ tag.name }}"></filter-react>
            {% endfor %}
        </div>
    </div>
    <div class="container flex col gap--16 gap-large-mobile align--start justify--center">
        <div class="grid grid--2 grid-gap--5 row grid--1-mobile">
            {% for key, project in projects %}
                <article class="flex col gap--5 article mb--20 {% for tag in project.tag.toArray %} {{ tag.slug }} {% endfor %}">
                    <a href="{{ path('app_show', {'slug': project.slug}) }}" class="relative" aria-label="{{ project.name }}">
                        {% if project.image is not empty %}
                            <img class="home__img home__img-post" src="{{ asset('uploads/projects/featured/large/') ~ project.image }}"
                                 loading="lazy" alt="{{ project.name }}">
                        {% else %}
                            <div class="home__img home__img-post stroke-dark--bg"></div>
                        {% endif %}
                        <div class="absolute pos-t--4 pos-l--4 flex row col-mobile gap--2">
                            {% for tag in project.tag.toArray %}
                                <tag-react data-color="{{ tag.color }}" data-content="{{ tag.name }}"></tag-react>
                            {% endfor %}
                        </div>
                        <svg class="absolute pos-center" viewBox="0 0 125 125" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle id="Ellipse 1" cx="62.5" cy="62.5" r="62.5" fill="white"/>
                            <path id="Vector" d="M49.5 75.5L74.5 50.5" stroke="#191919" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path id="Vector_2" d="M54.1875 50.5H74.5V70.8125" stroke="#191919" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </a>
                    <a href="{{ path('app_show', {'slug': project.slug}) }}" class="flex col gap--3">
                        <div class="flex row align--end justify--space-between">
                            <p class="text__l">
                                {{ project.name }}
                            </p>
                            <p class="text__m hide-mobile">
                                {{ project.category }}
                            </p>
                        </div>
                        <div class="flex col align--start justify--start gap--4">
                            <p class="primary-grey text__m">
                                {{ project.excerpt }}
                            </p>
                            <p class="text__m display-mobile">
                                {{ project.category }}
                            </p>
                        </div>
                    </a>
                </article>
            {% endfor %}
        </div>
    </div>

{% endblock %}