src/Entity/Legal.php
<?php

namespace App\Entity;

use App\Repository\LegalRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LegalRepository::class)]
class Legal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $legal_notice = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $privacy_policy = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $cookies = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLegalNotice(): ?string
    {
        return $this->legal_notice;
    }

    public function setLegalNotice(?string $legal_notice): static
    {
        $this->legal_notice = $legal_notice;

        return $this;
    }

    public function getPrivacyPolicy(): ?string
    {
        return $this->privacy_policy;
    }

    public function setPrivacyPolicy(?string $privacy_policy): static
    {
        $this->privacy_policy = $privacy_policy;

        return $this;
    }

    public function getCookies(): ?string
    {
        return $this->cookies;
    }

    public function setCookies(?string $cookies): static
    {
        $this->cookies = $cookies;

        return $this;
    }
}

src/Form/LegalType.php
<?php

namespace App\Form;

use App\Entity\Legal;
use Eckinox\TinymceBundle\Form\Type\TinymceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LegalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('legal_notice', TinymceType::class, [
                'label' => 'Mentions Légales',
                'attr' => [
                    'class' => 'form-textarea',
                    'placeholder' => 'Mentions Légales',
                    'plugins' => 'advlist autolink link table lists'
                ],
                'label_attr' => [
                    'class' => 'form-label'
                ],
                'required' => false
            ])
            ->add('privacy_policy', TinymceType::class, [
                'label' => 'Politique de Confidentialité',
                'attr' => [
                    'class' => 'form-textarea',
                    'placeholder' => 'Politique de Confidentialité',
                    'plugins' => 'advlist autolink link table lists'
                ],
                'label_attr' => [
                    'class' => 'form-label'
                ],
                'required' => false
            ])
            ->add('cookies', TinymceType::class, [
                'label' => 'Cookies',
                'attr' => [
                    'class' => 'form-textarea',
                    'placeholder' => 'Cookies',
                    'plugins' => 'advlist autolink link table lists'
                ],
                'label_attr' => [
                    'class' => 'form-label'
                ],
                'required' => false
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Enregistrer',
                'attr' => [
                    'class' => 'btn'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Legal::class,
        ]);
    }
}

src/Controller/Admin/LegalController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Faq;
use App\Entity\Legal;
use App\Form\FaqType;
use App\Form\LegalType;
use App\Repository\FaqRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[\Symfony\Component\Routing\Annotation\Route('/admin/legal', name: 'app_admin_legal_')]
class LegalController extends AbstractController
{
    private EntityManagerInterface $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    #[Route('/edit/{id}', name: 'edit', methods: ['POST', 'GET'])]
    public function editLegal(Legal $legal, Request $request): Response
    {
        $form = $this->createForm(LegalType::class, $legal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($legal);
            $this->em->flush();
            $this->addFlash('success', 'Mentions éditées avec succès');
            return $this->redirectToRoute('app_admin_legal_edit', ['id' => $legal->getId()]);
        }

        return $this->render('admin/legal/edit.html.twig', [
            'form' => $form,
        ]);
    }

}

templates/legal/cookies.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Cookies - {{ parent() }}
{% endblock %}

{% block meta %}
    <meta name="description" content="Vous souhaitez recevoir un devis sur mesure ? Remplissez le formulaire de contact et parlez-nous de votre projet. Nous avons hâte d'écouter votre projet.">
    <meta property="og:title" content="Contact - Studio Khi" />
    <meta property="og:description" content="Vous souhaitez recevoir un devis sur mesure ? Remplissez le formulaire de contact et parlez-nous de votre projet. Nous avons hâte d'écouter votre projet." />
    <meta property="og:url" content="https://studiokhi.com{{ path('app_cookies') }}" />
    {{ parent() }}
    <meta name="robots" content="noindex">
{% endblock %}

{% block body %}

    <section class="container__large border--bottom border-stroke-light">
        <div class="container">
            <h1>Politique de Cookies</h1>
        </div>
    </section>
    <section class="container text__m flex col gap--8">
        {{ legal.cookies|raw }}
    </section>

{% endblock %}

templates/legal/legal-notice.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Mentions Légales - {{ parent() }}
{% endblock %}

{% block meta %}
    <meta name="description" content="Vous souhaitez recevoir un devis sur mesure ? Remplissez le formulaire de contact et parlez-nous de votre projet. Nous avons hâte d'écouter votre projet.">
    <meta property="og:title" content="Contact - Studio Khi" />
    <meta property="og:description" content="Vous souhaitez recevoir un devis sur mesure ? Remplissez le formulaire de contact et parlez-nous de votre projet. Nous avons hâte d'écouter votre projet." />
    <meta property="og:url" content="https://studiokhi.com{{ path('app_legal_notice') }}" />
    {{ parent() }}
    <meta name="robots" content="noindex">
{% endblock %}

{% block body %}

    <section class="container__large border--bottom border-stroke-light">
        <div class="container">
            <h1>Mentions Légales</h1>
        </div>
    </section>
    <section class="container text__m flex col gap--8">
        {{ legal.legalNotice|raw }}
    </section>

{% endblock %}

templates/legal/privacy-policy.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Politique de Confidentialité - {{ parent() }}
{% endblock %}

{% block meta %}
    <meta name="description" content="Vous souhaitez recevoir un devis sur mesure ? Remplissez le formulaire de contact et parlez-nous de votre projet. Nous avons hâte d'écouter votre projet.">
    <meta property="og:title" content="Contact - Studio Khi" />
    <meta property="og:description" content="Vous souhaitez recevoir un devis sur mesure ? Remplissez le formulaire de contact et parlez-nous de votre projet. Nous avons hâte d'écouter votre projet." />
    <meta property="og:url" content="https://studiokhi.com{{ path('app_privacy_policy') }}" />
    {{ parent() }}
    <meta name="robots" content="noindex">
{% endblock %}

{% block body %}

    <section class="container__large border--bottom border-stroke-light">
        <div class="container">
            <h1>Politique de Confidentialité</h1>
        </div>
    </section>
    <section class="container text__m flex col gap--8">
        {{ legal.privacyPolicy|raw }}
    </section>

{% endblock %}